version: '3'
services:

  nginx:
    container_name: nginx
    build: requirements/nginx
    restart: always
    ports:
      - "443:443"
    env_file:
      - .env
    networks:
      - docker-network
    #volumes:
    #  - wp_volume:/var/www/html
    #  - ./log/nginx:/var/log/nginx
    #depends_on:
    #  - wordpress

#  wordpress:
#    image: wordpress

  mariadb:
    container_name: mariadb
    build:
      context: requirements/mariadb
      args:
       - MYSQL_DATABASE=${MYSQL_DATABASE}
       - MYSQL_USER=${MYSQL_USER}
       - MYSQL_PASSWORD=${MYSQL_PASSWORD}
       - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    env_file:
      - .env
#    environment:
#      MARIADB_ROOT_PASSWORD: tester

volumes:
  wp_volume:
    driver: local
networks:
  docker-network: