version: '3'
services:

  nginx:
#    image: nginx
    build: requirements/nginx
    restart: on-failure
    ports:
      - "443:443"
    env_file:
      - .env
    networks:
      - docker-network
    #volumes:
    #  - wp_volume:/var/www/html
    #  - ./log/nginx:/var/log/nginx
    #depends_on:
    #  - wordpress

#  wordpress:
#    image: wordpress

#  mariadb:
#    image: mariadb
#    environment:
#      MARIADB_ROOT_PASSWORD: tester

volumes:
  wp_volume:
    driver: local
networks:
  docker-network: