version: '3'
services:

  nginx:
    container_name: nginx
    build: requirements/nginx
    restart: always
    ports:
      - "443:443"
    env_file:
      - .env
    networks:
      - docker-network #fait le lien entre les containers
    volumes:
     - website:/var/www/wordpress
    depends_on:
     - mariadb
     - wordpress

  mariadb:
    container_name: mariadb
    build:
      context: requirements/mariadb
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    env_file:
      - .env
    networks:
      - docker-network
    volumes:
      - database:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 2s
      timeout: 10s
      retries: 4
      start_period: 10s

  wordpress:
    container_name: wordpress
    build:
      context: requirements/wordpress
    restart: always
    env_file:
      - .env
    environment:
       WORDPRESS_DB_HOST: mariadb
       WORDPRESS_DB_USER: ${MYSQL_USER}
       WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - mariadb
    networks:
      - docker-network
    expose:
      - "9000"
    volumes:
      - website:/var/www/wordpress

volumes:
  website:
    name: website
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '${HOME}/data/website'
  database:
    name: database
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '${HOME}/data/database'
networks:
  docker-network: